GRADES = (('', '-'),
          ('9', '9'),
          ('10', '10'),
          ('11', '11'),
          ('12', '12'),
          )
DREAM_DIRECTORS = (('', '-'),
                   ('ben.kimmerle', 'Ben'),
                   ('carrie.sangiovanni', 'Carrie'),
                   ('christian.shaboo', 'Christian'),
                   ('jessica.valoris', 'Jess'),
                   ('justin.zeigler', 'Justin'),
                   ('lamarr.womble', 'Lamarr'),
                   ('malia.west', 'Malia'),
                   ('nikhita', 'Nikhita'),
                   ('paula.ramirez', 'Paula'),
                   ('scotty.crowe', 'Scotty'),
                   ('william.jenkins', 'William'),
                   ('zaki', 'Zaki'),
                   )
