# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-17 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module0', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module0',
            options={'verbose_name': 'Module 1 Data', 'verbose_name_plural': 'Module 1 Data'},
        ),
    ]
