# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dream_director',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default=9, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default=9, max_length=256),
            preserve_default=False,
        ),
    ]
