# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-09 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0003_user_has_tou'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='access_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='max_limit',
            field=models.IntegerField(default=3),
        ),
    ]
