# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0003_auto_20170217_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ArchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('arch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_app.ArchetypesModel')),
            ],
        ),
        migrations.CreateModel(
            name='CheetahSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=128)),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_app.ArchetypesModel')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=256)),
                ('answer_yes', models.CharField(max_length=256, null=True)),
                ('answer_no', models.CharField(max_length=256, null=True)),
                ('weight_yes', models.FloatField(default=1.0)),
                ('weight_no', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='commitment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='commitment_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decisiontypes',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_app.Problem'),
        ),
        migrations.AddField(
            model_name='archtype',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_app.Problem'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='area_app.QuestionModel'),
        ),
    ]
