# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area_app', '0004_auto_20170410_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='problem',
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
