# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-09 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0004_auto_20190309_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_counter',
            field=models.IntegerField(default=0, help_text='Number of current attempts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_override',
            field=models.BooleanField(default=False, help_text='When true, ignore the max limit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_limit',
            field=models.IntegerField(default=3, help_text='Maximum access limit per user'),
        ),
    ]
