# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0005_auto_20170416_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='weight_no',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='weight_yes',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='why',
            field=models.CharField(default='', max_length=256),
        ),
    ]
