# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-07 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0006_whitelistdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='', help_text='User organization if set', max_length=40),
        ),
    ]
