# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0006_auto_20170416_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
