# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0008_auto_20170416_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='success',
            field=models.TextField(default=''),
        ),
    ]
