# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0009_auto_20170416_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='success',
            field=models.CharField(max_length=255),
        ),
    ]
