# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0010_auto_20170416_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
