# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0011_question_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept1', models.CharField(default='', max_length=256)),
                ('concept2', models.CharField(default='', max_length=256)),
                ('concept3', models.CharField(default='', max_length=256)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_app.Problem', unique=True)),
            ],
        ),
    ]
