# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(null=True)),
                ('step', models.CharField(default='', max_length=20)),
                ('answers', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Course')),
            ],
        ),
    ]
