# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_module2'),
    ]

    operations = [
        migrations.AddField(
            model_name='module2',
            name='biases',
            field=models.TextField(default=''),
        ),
    ]
