# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-22 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_module2_biases'),
    ]

    operations = [
        migrations.AddField(
            model_name='module2',
            name='nylah_bias',
            field=models.CharField(default='', max_length=40),
        ),
    ]
