# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0004_module2_nylah_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='module2',
            name='evidence0',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='module2',
            name='evidence1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='module2',
            name='evidence2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
