# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-30 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0005_auto_20171128_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course Taker'},
        ),
        migrations.AlterModelOptions(
            name='module1',
            options={'verbose_name': 'Module 1 Data', 'verbose_name_plural': 'Module 1 Data'},
        ),
        migrations.AlterModelOptions(
            name='module2',
            options={'verbose_name': 'Module 2 Data', 'verbose_name_plural': 'Module 2 Data'},
        ),
    ]
