# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0002_auto_20171007_1059'),
        ('decisions', '0007_auto_20180124_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(null=True)),
                ('step', models.CharField(default='', max_length=20)),
                ('answers', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Course')),
            ],
            options={
                'verbose_name': 'Module 0 Data',
                'verbose_name_plural': 'Module 0 Data',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('module0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Module0')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module0_question', to='area_app.QuestionModel')),
            ],
        ),
    ]
