# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0008_module0_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='module0',
            name='archetype',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='module0',
            name='psp_correct',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='module0',
            name='work_on',
            field=models.CharField(default='', max_length=255),
        ),
    ]
