# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0010_studentclass_studentclassstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentclassstudent',
            name='current_module',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentclassstudent',
            name='joined_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
