# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0011_auto_20180527_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='starting_module',
            field=models.IntegerField(default=0),
        ),
    ]
