# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-30 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0013_auto_20180527_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_module',
            field=models.IntegerField(default=0),
        ),
    ]
