# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-31 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0014_course_current_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module0',
            name='course',
        ),
        migrations.RemoveField(
            model_name='module1',
            name='course',
        ),
        migrations.RemoveField(
            model_name='module2',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module0',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        #TODO: Migrate data and delete
        #        migrations.RunSQL(''),
        #migrations.DeleteModel(
        #    name='Module0',
        #),
        #migrations.DeleteModel(
        #    name='Module1',
        #),
        #migrations.DeleteModel(
        #    name='Module2',
        #),
        #migrations.DeleteModel(
        #    name='Question',
        #),
    ]
