# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-09 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0015_auto_20180531_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module0',
        ),
        migrations.DeleteModel(
            name='Module1',
        ),
        migrations.DeleteModel(
            name='Module2',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
