# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-21 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decisions', '0009_auto_20180422_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(null=True)),
                ('step', models.CharField(default='', max_length=20)),
                ('answers', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Course')),
            ],
            options={
                'verbose_name': 'Module 3 Data',
                'verbose_name_plural': 'Module 3 Data',
            },
        ),
    ]
