from django.conf.urls import url, include
import views
urlpatterns = [
    url(r'^$', views.intro, name='Module Start'),
    url(r'^intro/?$', views.intro, name='Module Intro'),
    url(r'^restart/?', views.restart, name='Module Restart'),
    url(r'^review/?$', views.review, name='Module Review'),
    url(r'^map/?$', views.map, name='Module Map'),
    url(r'^instructions/?$', views.instructions, name='Module Instructions'),

    url(r'^game/?$', views.game, name='Module 2 Game'),
    url(r'^game_end/?$', views.game_end, name='Module 2 Game End'),
    url(r'^explain/?$', views.explain, name='Module 2 Explanation'),
    url(r'^bias/?$', views.bias, name='Module 2 Cognitive Biases'),
    url(r'^game_results/?$', views.game_results, name='Module 2 Game Results'),
    url(r'^game2_intro/?$', views.game2_intro, name='Module 2 Game 2 Introduction'),
    url(r'^game?$', views.game2, name='Module 2 Game 2'),
    url(r'^nylah1/?$', views.nylah1, name='Module 2 Nylah'),
    url(r'^nylah?$', views.nylah2, name='Module 2 Nylah'),
    url(r'^nylah3/?$', views.nylah3, name='Module 2 Nylah'),
    url(r'^nylah4/?$', views.nylah4, name='Module 2 Nylah'),
    url(r'^nylah5/?$', views.nylah5, name='Module 2 Nylah'),
    url(r'^nylah50/?$', views.nylah50, name='Module 2 Nylah'),
    url(r'^nylah51/?$', views.nylah51, name='Module 2 Nylah'),
    url(r'^nylahotherfacts/?$', views.nylahotherfacts, name='Module 2 Nylah'),
    url(r'^nylah5?$', views.nylah52, name='Module 2 Nylah'),
    url(r'^nylah6/?$', views.nylah6, name='Module 2 Nylah'),
    url(r'^nylah61/?$', views.nylah61, name='Module 2 Nylah'),
    url(r'^nylah7/?$', views.nylah7, name='Module 2 Nylah'),
    url(r'^nylah8/?$', views.nylah8, name='Module 2 Nylah'),
    url(r'^nylah_cc/?$', views.nylah_cc, name='Module 2 Nylah Critical Concepts'),
    url(r'^nylah_cc_facts/?$', views.nylah_cc_facts, name='Module 2 Nylah Critical Concept Facts'),
    url(r'^nylah_cc_assumptions/?$', views.nylah_cc_assumptions,
        name='Module 2 Nylah Critical Concept Assumptions'),
    url(r'^nylah_cc_evidence/?$', views.nylah_cc_evidence, name='Module 2 Nylah Critical Concept Evidence'),
    url(r'^cc/?$', views.cc, name='Module 2 Critical Concepts'),
    url(r'^cc_edit/?$', views.cc_edit, name='Module 2 Edit Critical Concepts'),
    url(r'^steps/?$', views.steps, name='Module 2 Moving into Action'),
    url(r'^steps2/?$', views.steps2, name='Module 2 Moving into Action'),
    url(r'^steps3/?$', views.steps3, name='Module 2 Moving into Action'),
    url(r'^steps4/?$', views.steps4, name='Module 2 Moving into Action'),
    url(r'^cheetah/?$', views.cheetah, name='Module 2 Cheetah Sheet'),
    url(r'^summary/?$', views.summary, name='Module 2 Summary'),

    url(r'^summary/?$', views.summary, name='Module Summary'),
]
