# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='intro_note',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
