# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0005_module2_my_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='module2',
            name='my_bias_impact',
            field=models.TextField(default=''),
        ),
    ]
