# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0007_module2_my_bias_remedy'),
    ]

    operations = [
        migrations.AddField(
            model_name='module2',
            name='answers2',
            field=models.TextField(default=''),
        ),
    ]
