# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0008_module2_answers2'),
    ]

    operations = [
        migrations.AddField(
            model_name='module2',
            name='my_remedy',
            field=models.TextField(default=''),
        ),
    ]
