# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decisions', '0015_auto_20180531_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(null=True)),
                ('step', models.CharField(default='', max_length=20)),
                ('answers', models.TextField(default='')),
                ('cc0', models.CharField(default='', max_length=255)),
                ('cc1', models.CharField(default='', max_length=255)),
                ('cc2', models.CharField(default='', max_length=255)),
                ('decision', models.CharField(default='', max_length=255)),
                ('cc', models.CharField(default='', max_length=255)),
                ('cc_not', models.CharField(default='', max_length=255)),
                ('decision_buddy', models.CharField(default='', max_length=80)),
                ('decision_buddy_email', models.EmailField(default='', max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Course')),
            ],
            options={
                'verbose_name': 'Module 1 Data',
                'verbose_name_plural': 'Module 1 Data',
            },
        ),
    ]
