# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decisions', '0015_auto_20180531_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(null=True)),
                ('step', models.CharField(default='', max_length=50, verbose_name='Current Step')),
                ('answers', models.TextField(default='', verbose_name='Game Answers')),
                ('sample_cc', models.TextField(default='', verbose_name='What made the decision successful?')),
                ('practice_cc1', models.TextField(default='', verbose_name='Answers without CC')),
                ('practice_cc2', models.TextField(default='', verbose_name='Answers with CC')),
                ('decision', models.CharField(default='', max_length=255, verbose_name='Your decision problem')),
                ('decision_as_question', models.CharField(default='', max_length=255, verbose_name='Your decision problem as a question')),
                ('living', models.CharField(default='', max_length=80, verbose_name='Where to live?')),
                ('why', models.TextField(default='', verbose_name='Why decisions were easy or difficult?')),
                ('cc', models.TextField(default='', max_length=255, verbose_name='Re-framed as questions')),
                ('cc_not', models.TextField(default='', max_length=255)),
                ('cc_occurred', models.TextField(default='', verbose_name='They occurred because the decision was successful')),
                ('decision_buddy', models.CharField(default='', max_length=80)),
                ('decision_buddy_email', models.EmailField(default='', max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Course')),
            ],
            options={
                'verbose_name': 'Module 1 Data',
                'verbose_name_plural': 'Module 1 Data',
            },
        ),
    ]
