# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module1',
            name='decision_as_question',
        ),
        migrations.AlterField(
            model_name='module1',
            name='answers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='module1',
            name='cc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='module1',
            name='cc_not',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='module1',
            name='cc_occurred',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='module1',
            name='decision',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='module1',
            name='living',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='module1',
            name='practice_cc1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='module1',
            name='practice_cc2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='module1',
            name='sample_cc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='module1',
            name='step',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='module1',
            name='why',
            field=models.TextField(default=''),
        ),
    ]
