# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-09 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_auto_20181006_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module1',
            name='cc',
            field=models.TextField(default=''),
        ),
    ]
